version: '3.4'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier

  urlshortener:
    image: urlshortener
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
